// Embedded click set, resampled once to the host rate (off the audio thread).
#pragma once
#include <cstdint>
#include <vector>

namespace kikset {

struct ClickData {
    const char* name;
    const int16_t* samples;  // 48 kHz, mono
    int length;
};
extern const ClickData kClicks[];  // generated by cmake/EmbedResources.cmake
extern const int kClickCount;

class ClickBank {
public:
    void init(double sampleRate);
    int count() const { return int(clicks_.size()); }
    const char* name(int i) const;
    // Linear interpolation at fractional position (samples since trigger).
    float at(int index, double pos) const;
    int length(int index) const;

private:
    std::vector<std::vector<float>> clicks_;
};

}  // namespace kikset
